"""Database package — exports Base and all 25 ORM models."""

from app.db.base import Base
from app.db.models import (
    APIKey,
    ActiveExploit,
    AssetChange,
    AssetSnapshot,
    AuditLog,
    BaselineSnapshot,
    CacheEntry,
    ChangeNotification,
    ComplianceEvidence,
    ComplianceFinding,
    ComplianceReport,
    DNSRecord,
    DataLeak,
    DomainTechnology,
    HTTPHeader,
    ISPLocation,
    KnownVulnerability,
    MalwareIndicator,
    PortScan,
    RiskScore,
    SavedReport,
    ScanProgress,
    ScanRun,
    ScanRunnerMetadata,
    ScannerIntegration,
    ScheduledScan,
    ServiceSignature,
    Subdomain,
    Technology,
    ThreatIntelData,
    VendorMetadata,
    Vulnerability,
    VulnerabilityMetadata,
    WebsiteSnapshot,
)

__all__ = [
    "Base",
    # Core scanning
    "ScanRun",
    "Subdomain",
    "PortScan",
    "Vulnerability",
    "HTTPHeader",
    # Intelligence
    "Technology",
    "DomainTechnology",
    "VulnerabilityMetadata",
    "DNSRecord",
    "ISPLocation",
    "ThreatIntelData",
    # Compliance & reporting
    "ComplianceReport",
    "ComplianceFinding",
    "RiskScore",
    "AuditLog",
    "AssetSnapshot",
    # Change tracking
    "AssetChange",
    "ChangeNotification",
    "WebsiteSnapshot",
    # Integration & system
    "ScannerIntegration",
    "ScanRunnerMetadata",
    "APIKey",
    "SavedReport",
    "ScheduledScan",
    "KnownVulnerability",
    # Supplementary phase 3-5 models
    "ServiceSignature",
    "VendorMetadata",
    "DataLeak",
    "ActiveExploit",
    "MalwareIndicator",
    "ComplianceEvidence",
    "BaselineSnapshot",
    "ScanProgress",
    "CacheEntry",
]
